### ISSUE TITLE
MinSwap audit link does lead to 404

### ISSUE THREAD

**Issue by nielstron** [DefiLlama/fees-server#1]
The link to the audit of the MinSwap protocol on Cardano does not lead to a valid audit file (it goes to 404)

https://github.com/DefiLlama/fees-server/blob/5941938a1627d3bed00d590937f329e5a0b6c3e6/src/utils/protocols/data2.ts#L1895

**Comment by 0xngmi** [comment]
wrong repo, you should open this issue in https://github.com/DefiLlama/defillama-server

**Comment by nielstron** [comment]
Thanks
