### ISSUE TITLE
Wingriders "Audit" is a blog article, not the original audit 

### ISSUE THREAD

**Issue by nielstron** [DefiLlama/fees-server#2]
The real audit is listed here: https://www.certik.com/projects/wingriders
The corresponding github repository by CertiK leads to 404 (https://github.com/WingRiders/core-contracts/tree/audit). No complete audit is provided anywhere.

https://github.com/DefiLlama/fees-server/blob/5941938a1627d3bed00d590937f329e5a0b6c3e6/src/utils/protocols/data2.ts#L4229

**Comment by 0xngmi** [comment]
wrong repo again: https://github.com/DefiLlama/defillama-server

**Comment by nielstron** [comment]
Thanks!
